### PR TITLE
Done isort, black, flake8 in README-1.3

### PR DESCRIPTION
**Pull request by gerish01**
Shell output:
gerish@TIGER04469:~/MLE-Training/MLE-Training$ flake8 README
(it didn't showed any errors using flake8)

Formatted the Python script using black, isort, and fixed errors identified by flake8.
The Python script (FILENAME: README) was reformatted to adhere to consistent coding standards and improve readability.

**STEPS**
1. Installed and configured black, isort, and flake8.
2. Used black, isort and Ran flake8 to identified and fixed any errors.

**Command Used**

1. black README
2. isort REAME
3. flake8 README

### CODE REVIEW

**Comment by sarath-srinivas** [comment]
Please link the relevant *issue* for this PR..

**Review by sarath-srinivas — CHANGES_REQUESTED** [review]
Please include any config files that are used for the formatting/linting tools

**Comment by gerish01** [comment]
This pull request addresses the issues described in [Issue #4](https://github.com/gerish01/MLE-Training/pull/4#issue-2190185499) and configuration files for isort, black, and flake8. These files have been added to ensure consistent formatting and linting across the project.

**Review by sarath-srinivas — CHANGES_REQUESTED** [review]
Please do not ignore rules in the flake config. The whole point of flake is to fix the linting errors and not ignore them.. Use black, isort to autoformat such that flake does not give any errors. (you can ignore warnings but not errors.)

**Comment by gerish01** [comment]
Sir , Actually This is Assignement- 1.3 in which they told us to (Create a new branch fix/<issue-id>/manual-refactor from v0.1 (created in the last exercise of previous module). Use the tools black and isort to reformat the code. Once done, run flake8 and fix any errors identified by the tool.) So, I ran flake8 it does not gave any errors. 

Filename without Errors README, branch name fix/issue-2190162778/manual-refactor

But in Assignment 1.4, I am working on Auto-formatting.

**Review by sarath-srinivas — APPROVED** [review]

**Pull request merged**
